version: '3.0'

services:
  app:
    build: .
    environment:
      - RAILS_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: APP_DB
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  mysql_data:
